feat(add): mini projects to YAML workflow and update python README to include it

diff --git a/.github/workflows/publish-subtrees.yml b/.github/workflows/publish-subtrees.yml
--- a/.github/workflows/publish-subtrees.yml
+++ b/.github/workflows/publish-subtrees.yml
@@ -36,3 +36,6 @@ jobs:
 
       - name: Push python worshop 2
         run: git subtree push --prefix=python/workshop_2 origin project/python/workshop_2 || echo "No changes or error on workshop_2"
+      
+      - name: Push python mini projects
+        run: git subtree push --prefix=python/mini-projects origin project/python/mini-projects || echo "No changes or error on mini projects"
